trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# 2. Install project dependencies
- script: |
    npm install
    npm install -g @angular/cli@17
  displayName: 'Install Dependencies'

# 3. Build the Angular application
- script: |
    ng build --configuration=production
  displayName: 'Build Angular App'

# 4. Prepare and publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/comman'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

# 5. Deploy to Azure Static Web Apps
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    api_location: ''
    output_location: 'dist/comman'
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APP_TOKEN)
  displayName: 'Deploy to Azure Static Web Apps'