export class LandingPlace {
    Id!: number
    Address!: string
    City!: string
    State!: string
    Zip!: string
    Longitude!: number
    Latitude!: number
    Type!: string
    Units!: string
    ZoningCode!: string
    LandUse!: string
    BuildingSizeSf!: number
    StreetViewURL!: string
    ForSalePrice!: string
    Description!: string
    UploadDate!: string
    Class!: string
    SecondaryType!: string
    ListingType!: string
    MainImage!: string
    PopulationDensity!: number
    ForLeasePrice!: string
    Employees!: string
    HouseholdIncome!: string
    Suburban!: boolean
    Urban!: boolean
    CenterName!: string
    LeaseType!: string
    SiteSelectionReason!: string
    Parking!: string
    Suite!: string
    Heading!: number
    Images!: string
    Notes!: string
    Pitch!: number
    StreetLatitude!: number
    StreetLongitude!: number
    Extras!: string
    ShoppingCenterId!: number
    AverageRent!: string
    FAR!: string
    Stories!: string
    SitePlan!: string
    UnitTypeId!: number
    DocsLink!: string
    ShoppingCenters!: ShoppingCenter[]
  }
  
  export interface ShoppingCenter {
    Id: number
    CenterName: string
    CenterType: string
    CenterAddress: string
    CenterCity: string
    CenterState: string
    StreetViewURL: string
    Latitude: number
    Longitude: number
    MainImage: string
    Heading: number
    Pitch: number
    StreetLatitude: number
    StreetLongitude: number
    OtherPlaces: OtherPlace[]
  }
  export interface OtherPlace {
    Id: number
    Address: string
    City: string
    State: string
    Zip: string
    StreetViewURL: string
    Longitude: number
    Latitude: number
    Type: string
    Units: string
    ZoningCode: string
    LandUse: string
    BuildingSizeSf: number
    ForSalePrice: string
    Description: string
    UploadDate: string
    Class: string
    SecondaryType: string
    ListingType: string
    MainImage: string
    PopulationDensity: string
    ForLeasePrice: string
    Employees: string
    HouseholdIncome: string
    Suburban: boolean
    Urban: boolean
    CenterName: string
    LeaseType: string
    SiteSelectionReason: string
    Parking: string
    Suite: string
    Heading: number
    Images: string
    Notes: string
    Pitch: number
    StreetLatitude: number
    StreetLongitude: number
    Extras: string
    ShoppingCenterId: number
  }
  
  